### ISSUE TITLE
wepy new x新建项目出错

### ISSUE THREAD

**Issue by tao2581** [wepyjs/wepy#15]
![image](https://cloud.githubusercontent.com/assets/3303524/21803813/cb6edee8-d766-11e6-8f23-1d6d8c75f5ee.png)

```
[18:58:28] [完成] 安装依赖完成
[18:58:28] [执行] 执行命令: wepy build
[18:58:28] [信息] 可能需要几分钟, 请耐心等待...
/Users/tds/webroot/weapp/Weapp/wepy.config.js:2
let prod = process.env.NODE_ENV === 'production';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.getConfig (/usr/local/lib/node_modules/wepy-cli/lib/util.js:294:22)
    at Object.build (/usr/local/lib/node_modules/wepy-cli/lib/compile.js:177:37)
    at Command.<anonymous> (/usr/local/lib/node_modules/wepy-cli/lib/wepy.js:162:23)
[18:58:30] [错误] 代码编译出错
```

![image](https://cloud.githubusercontent.com/assets/3303524/21803837/e7e448b0-d766-11e6-88b4-f4c522ebc8de.png)

改成  var prod = process.env.NODE_ENV === 'production';
继续 build 成功

**Comment by Gcaufy** [comment]
`'use strict';` 或者改成var都可以，但是建议升级一下NodeJS版本
参考： https://github.com/wepyjs/wepy/issues/2
