### ISSUE TITLE
require有疑问 使用node-rsa, 报not defined

### ISSUE THREAD

**Issue by IntroTheDawn** [wepyjs/wepy#150]
let NodeRSA = require('node-rsa');

微信开发者工具返回信息
Possible Unhandled Promise Rejection: Error: module "npm/node-rsa/src/NodeRSA.js" is not defined
    at require (http://423107681.appservice.open.weixin.qq.com/WAService.js:7:17718)
    at http://423107681.appservice.open.weixin.qq.com/WAService.js:7:17573
    at GroupBuysIndex._callee$ (http://423107681.appservice.open.weixin.qq.com/pages/gb-index.js:151:27)
    at tryCatch (http://423107681.appservice.open.weixin.qq.com/npm/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (http://423107681.appservice.open.weixin.qq.com/npm/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (http://423107681.appservice.open.weixin.qq.com/npm/regenerator-runtime/runtime.js:116:21)
    at step (http://423107681.appservice.open.weixin.qq.com/pages/gb-index.js:19:191)
    at http://423107681.appservice.open.weixin.qq.com/pages/gb-index.js:19:437
    at doResolve (http://423107681.appservice.open.weixin.qq.com/npm/promise-polyfill/promise.js:113:7)
    at new Promise (http://423107681.appservice.open.weixin.qq.com/npm/promise-polyfill/promise.js:24:5)

**Comment by Gcaufy** [comment]
`node-rsa` 这个模块依赖于 `crypto`和`constants`模块，而这两个模块是 Node.js 的内置模块，所以 `node-rsa` 在小程序环境中是不可用的。
