### ISSUE TITLE
如何更换eslint 更换代码风格？

### ISSUE THREAD

**Issue by wanghaixu** [wepyjs/wepy#171]
我想使用airbnb-base风格，该如何做？

**Comment by Gcaufy** [comment]
修改目录下的`.eslintrc.js`文件

**Comment by wanghaixu** [comment]
我安装完所需的npm包后，把.eslintrc.js 中的extends改为airbnb-base；运行npm run dev ,出现错误信息：        

E:\work_stude\wepy-project\node_modules\eslint\lib\config\config-file.js:434
            throw e;
            ^

Error: E:\work_stude\wepy-project\node_modules\.npminstall\eslint-config-airbnb-base\11.2.0\eslint-config-airbnb-base\rules\style.js:
        Configuration for rule "no-restricted-syntax" is invalid:
        Value "[object Object]" is the wrong type.

Referenced from: airbnb-base
Referenced from: E:\work_stude\wepy-project\.eslintrc.js
    at validateRuleOptions (E:\work_stude\wepy-project\node_modules\eslint\lib\config\config-validator.js:109:15)
    at Object.keys.forEach.id (E:\work_stude\wepy-project\node_modules\eslint\lib\config\config-validator.js:156:13)
    at Array.forEach (native)
    at Object.validate (E:\work_stude\wepy-project\node_modules\eslint\lib\config\config-validator.js:155:35)
    at load (E:\work_stude\wepy-project\node_modules\eslint\lib\config\config-file.js:559:19)
    at configExtends.reduceRight.e (E:\work_stude\wepy-project\node_modules\eslint\lib\config\config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (E:\work_stude\wepy-project\node_modules\eslint\lib\config\config-file.js:408:28)
    at load (E:\work_stude\wepy-project\node_modules\eslint\lib\config\config-file.js:566:22)
    at configExtends.reduceRight.e (E:\work_stude\wepy-project\node_modules\eslint\lib\config\config-file.js:424:36)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! test@1.2.8 dev: `wepy build --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.2.8 dev script 'wepy build --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     wepy build --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\work_stude\wepy-project\npm-debug.log
