### ISSUE TITLE
build 报错

### ISSUE THREAD

**Issue by JZLeung** [wepyjs/wepy#2]
新建的项目，直接build的时候就报错了。
```
/Volumes/Data/Leung/Workspace/cnode/wepy.config.js:2
let prod = process.env.NODE_ENV === 'production';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.getConfig (/usr/local/lib/node_modules/wepy-cli/lib/util.js:225:22)
    at Object.build (/usr/local/lib/node_modules/wepy-cli/lib/compile.js:156:37)
    at Command.<anonymous> (/usr/local/lib/node_modules/wepy-cli/lib/wepy.js:130:23)
```

**Comment by Gcaufy** [comment]
好久没升级NODE版本了吧，升级一下新的node，应该是node版本问题。

`node -v` 看看。

**Comment by JZLeung** [comment]
好的，我晚上回去看看。

**Comment by Clect** [comment]
我想问一下，在我用wepy的时候，我bindtap点击，怎么获取AppData的值？
在点击的回调函数里面console(this)是undefined

**Comment by AlbertLiu-Breeze** [comment]
我的node版本是 4.4.3，依然不行，必须手动修改代码才能编译成功

**Comment by kiner-tang** [comment]
![image](https://cloud.githubusercontent.com/assets/10286961/21923584/df382de4-d9af-11e6-8908-edf14d3f4f56.png)

**Comment by Gcaufy** [comment]
@AlbertLiu-Breeze @kiner-tang `node 5+`, `npm 3+`

**Comment by kiner-tang** [comment]
我的可以了，真的是node版本太旧了

**Comment by wangmengHB** [comment]
我的node版本是8.9.4， 我也出现同样的问题，polyfill完全引入不进去，Promise，process等等undefined，场景是新建一个standard项目

**Comment by Gcaufy** [comment]
@wangmengHB  npm 的版本呢？
不会用到process的。。看看是哪里出了问题。

**Comment by YZFYZF** [comment]
我的node也是8以上  也是不行的  有解决的吗

**Comment by cdll** [comment]
y not use node@LTS?
