### ISSUE TITLE
使用pug模板语法，首行不能缩进

### ISSUE THREAD

**Issue by zhuowenli** [wepyjs/wepy#211]
使用pug模板语法，首行不能缩进，多个空格也不不行。
```pug
<template lang="pug">
    view.home
        swiper.swiper(
            indicator-dots="{{true}}"
            indicator-color="#fff"
            indicator-active-color="#ff4c4e"
            autoplay="{{true}}"
            interval="5000"
            duration="500"
        )
            block(wx:for="{{imgUrls}}" wx:key="{{index}}")
                swiper-item
                    image.swiper-image(src="{{item}}" mode="widthFix")
</template>
```

```
/Users/zhuowenli/demo/weapp-demo/node_modules/pug-parser/index.js:59
    throw err;
    ^

Error: Pug:2:1
    1|
  > 2|     view.home
-------^
    3|         swiper.swiper(
    4|             indicator-dots="{{true}}"
    5|             indicator-color="#fff"

unexpected token "indent"
    at makeError (/Users/zhuowenli/demo/weapp-demo/node_modules/pug-error/index.js:32:13)
    at Parser.error (/Users/zhuowenli/demo/weapp-demo/node_modules/pug-parser/index.js:53:15)
    at Parser.parseExpr (/Users/zhuowenli/demo/weapp-demo/node_modules/pug-parser/index.js:263:14)
    at Parser.parse (/Users/zhuowenli/demo/weapp-demo/node_modules/pug-parser/index.js:112:25)
    at parse (/Users/zhuowenli/meiya/demo/weapp-demo/node_modules/pug-parser/index.js:12:20)
    at Object.parse (/Users/zhuowenli/demo/weapp-demo/node_modules/pug/lib/index.js:126:22)
    at Function.loadString [as string] (/Users/zhuowenli/demo/weapp-demo/node_modules/pug-load/index.js:45:21)
    at compileBody (/Users/zhuowenli/demo/weapp-demo/node_modules/pug/lib/index.js:86:18)
    at Object.exports.compile (/Users/zhuowenli/demo/weapp-demo/node_modules/pug/lib/index.js:243:16)
    at Function.compiler.sync (/Users/zhuowenli/demo/weapp-demo/node_modules/wepy-compiler-pug/lib/index.js:30:28)
error Command failed with exit code 1.
```

如下，必须得把首行的空格移除才行，有强迫症的简直不能忍😂
```pug
<template lang="pug">
view.home
    swiper.swiper(
        indicator-dots="{{true}}"
        indicator-color="#fff"
        indicator-active-color="#ff4c4e"
        autoplay="{{true}}"
        interval="5000"
        duration="500"
    )
        block(wx:for="{{imgUrls}}" wx:key="{{index}}")
            swiper-item
                image.swiper-image(src="{{item}}" mode="widthFix")
</template>
```

**Comment by zhuowenli** [comment]
pug 代码一旦报错，会直接退出命令行~~

**Comment by Gcaufy** [comment]
fixed in 1.5.8
