### ISSUE TITLE
更新组件 Array 型的 props 时报错

### ISSUE THREAD

**Issue by krimeshu** [wepyjs/wepy#349]
假设有个列表组件 **list.wpy**，从父组件获取一个 `data` 属性用来绑定列表数据：

```html
<template>
  <view>
    <text>{{data.length}}</text>
  </view>
</template>

<script>
import wepy from 'wepy';

export default class List extends wepy.component {
  props = {
    data: {
      type: Array,
      default: []
    }
  };
}
</script>

```

**index.wpy** 引入它后，绑定 `data` 属性，该属性在 ajax 拿到数据后异步更新，这里用 `setTimeout` 模拟：

```html
<template>
  <view class="container">
    <list :data.sync="listData" />
  </view>
</template>

<script>
import wepy from 'wepy';

import List from './list';

export default class Index extends wepy.page {
  components = {
    list: List
  };

  data = {
    listData: []
  };

  onLoad() {
    setTimeout(() => {
      this.listData.push({});
      this.$apply();
    }, 200);
  }
}
</script>

```

结果执行到 `this.$apply()` 时就会抛出异常：

```
WAService.js:3 thirdScriptError
Maximum call stack size exceeded;at pages/index onLoad function;at setTimeout callback function
RangeError: Maximum call stack size exceeded
    at Object.$extend (http://270945985.appservice.open.weixin.qq.com/npm/wepy/lib/util.js:103:30)
    at Object.$extend (http://270945985.appservice.open.weixin.qq.com/npm/wepy/lib/util.js:151:45)
    at Object.$extend (http://270945985.appservice.open.weixin.qq.com/npm/wepy/lib/util.js:151:45)
    at Object.$extend (http://270945985.appservice.open.weixin.qq.com/npm/wepy/lib/util.js:151:45)
    at Object.$extend (http://270945985.appservice.open.weixin.qq.com/npm/wepy/lib/util.js:151:45)
    at Object.$extend (http://270945985.appservice.open.weixin.qq.com/npm/wepy/lib/util.js:151:45)
    at Object.$extend (http://270945985.appservice.open.weixin.qq.com/npm/wepy/lib/util.js:151:45)
    at Object.$extend (http://270945985.appservice.open.weixin.qq.com/npm/wepy/lib/util.js:151:45)
    at Object.$extend (http://270945985.appservice.open.weixin.qq.com/npm/wepy/lib/util.js:151:45)
    at Object.$extend (http://270945985.appservice.open.weixin.qq.com/npm/wepy/lib/util.js:151:45)
```

是 wepy 的组件暂时不支持 Array 类型的 props 吗？这种情况该怎么处理呢？

**Comment by krimeshu** [comment]
突然想到 data 算是保留字段来着，明天改了试试…

**Comment by SuperJolly** [comment]
wepy组件是支持Array类型的props的，把list组件props要传的data字段修改为其他名称，data是关键字，会被特殊处理。

**Comment by krimeshu** [comment]
确实是这个问题，之前写的小程序组件用了 data 字段，直接放在 wepy 组件里冲突了 XD。
话说还有些体验上的小问题想反馈，大家一般通过什么渠道联系作者呢？

**Comment by SuperJolly** [comment]
你就提issue就可以了，作者很快会看到的～
