### ISSUE TITLE
编译阶段错误：Cannot read property 'prefix' of null

### ISSUE THREAD

**Issue by wangzexi** [wepyjs/wepy#67]
现有组件引用关系：`page`->`typeMenu`->`Menu`。

发现，将`typeMenu`组件放在某些目录，比如非`src/components`目录中时，都会在编译时输出下面错误。
```
[18:17:49] [写入] WXSS: dist/pages/food/com/typeMenu.wxss
TypeError: Cannot read property 'prefix' of null
    at Document.nodeSerializeToString [as toString] (/usr/local/lib/node_modules/wepy-cli/node_modules/.0.1.27@xmldom/dom.js:920:22)
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-template.js:295:50
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

import的相对路径我都仔细检查过，没问题。

```javascript
// typeMenu.wpy

import wepy from 'wepy';
import Menu from '../../../components/menu';

export default class extends wepy.component {
    components = {
        Menu // 当注释掉此行时，报错消失
    };
```

想请教一下，产生这个错误的原因？

**Comment by liumin1128** [comment]
如果我没猜错的话，你的组件代码需要改成：
`components = {
            menu: Menu
    };`
原因可能是组件名，和变量冲突了

**Comment by wangzexi** [comment]
依然会错误：
```
[00:02:31] [写入] WXSS: dist/pages/food/com/typeMenu.wxss
TypeError: Cannot read property 'prefix' of null
    at Document.nodeSerializeToString [as toString] (/usr/local/lib/node_modules/wepy-cli/node_modules/.0.1.27@xmldom/dom.js:920:22)
    at /usr/local/lib/node_modules/wepy-cli/lib/compile-template.js:397:29
    at process._tickCallback (internal/process/next_tick.js:103:7)

```

```javascript
// typeMenu.wpy

import wepy from 'wepy';
import Menu111 from '../../../components/menu';

export default class extends wepy.component {
    components = {
            menu222: Menu111 // 当注释掉此行时，报错消失
    };
```

即便有这个报错，编译出的程序运行也完全正常，很神奇。😁

**Comment by sqaiyan** [comment]
我昨天遇到过， template里不能直接写component，需要用view包住一层，不知道你的是不是这个问题，可以试试看

**Comment by Gcaufy** [comment]
@liumin1128 
他的写法没有问题，可以写
```
components = {
    Menu,
}
```
因为这样可以编译为：
```
components = {
    Menu: Menu,
}
```

**Comment by Gcaufy** [comment]
@sqaiyan 你说的应该是另外一个问题，刚测试了一下，的确如此，如果直接写component会报`Cannot read property 'prefix' of null`
刚提交了一个commit修复了这个问题。

**Comment by wangzexi** [comment]
@liumin1128 测试过，应该不是大小写的问题。
@sqaiyan 我确实没有把组件包起来，还没来及测试。
@Gcaufy 原来问题出在这里，辛苦了辛苦了。🍭

**Comment by Gcaufy** [comment]
@wangzexi 
刚才把我的组件从`components`移动到`pages`文件夹中，所以我的组件引用变成了
`import Test from './../pages/test';`

但是经过测试，没有报错， 所以看看是不是是@sqaiyan 说的问题。

**Comment by Gcaufy** [comment]
https://github.com/wepyjs/wepy/issues/123
